language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install && npm test
script: npm run build
before_deploy: rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: YHBG/Y38SoUP0rXON6bVK9m+HvTuJ0WIyR+qBttbF+cRMYOPvC6rIqj1q3A59vw42iDw0O8dBNbSPajDLWCQsDytab6WikO7+5ZRwlEI+42N8LQZnYRcxeyzfXWzSljXAY1xHxVcyxYD/4NfYcGlAzWQCd13YSburN74o0L4zB4chIec0c8nqaRDqPOR8eCupV0AlKCP6MJaQvloWMJ6zNmvrLs7UvtLZtgzfU8eVVbMywLTestQm+O5nC82S6LhycLn+sxikLNU1oHFzy4MR0JT8GNVFBt8d6+SUWm0s/C9Bq/pHCWPI9O1g1jXeEo/idkJiFRv7nVpdYm0RXxlap2vmPelqv/noPqcf0pJZHDrRefeEmd0N3VTeDz3Kt6YiQ4MJDP0qqj00mtPLMc/b78P0GF8kFQb1yiiVEtYmj8foh4+QcqFeuJCWfk+QtxLWg6dPeNcjWX+A7Cv6bwUfnX5gEu7uyJzIcJP3FWxpycqs8UOMBY3LSfgOc3O33zsISc6sVmR/I1ZhPnX9YzBWbU3yISv3dBkxcJe4SZMGz58TDg3V6wEYrOJtUxdof/7N1o6KC31gvyDy8WLbgUgIYb1P0wCzeXQsabdfI9xV4MPQoyxmoUexF7dcD3AoYyF4fZOyHq96ROLY3+HudMUmL+7HcoVNt40+HEm3Yw5ciM=
  app:
    master: git-lucky-search
