language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
script: npm run build
before_deploy: rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: BYqJS2GpUK54S+XxdwX0Px2+yIi6ZwF4JAm0hSQggQQbORmTBI2GOTYZwdyMLm1V+Ps09CqVSURWG/SkQx/gGQv1tzcnSObd8K7nwz/Sg4snLu6ZR7ZREYpTTUdXmyhPoCnUsia7EnJe3J6/Pz0dCvs04kO9R4kQFoXPB2yJOX3ngHFlXQLe7Bpcl/lTDuhpg3HBIo5BDaT4mDZKRKWJ1skWeXcBTFFmPbFVnyxqYVDjGL5+CdfQTvbfYWvRgD1ARW3T/8FSwvQsp8X5qA3yfuLh9P5ADeuorIxwn2OKixDAlNwVDWOSPSr8DgFLn7ARtBdZBmIYJRTzKlRng+Jqw0z1Nb0Zqd88L/vTN6nnUhml4eva5ZjDpXkV6wVsRwvmnwRaDSZdpoIs/NX0hPGPuJu+4veoSoVDdxTw2BL2VytdLxHIlH12D2io6ESwvrpobuyG6pbpia0oCbkYsXRuVVHKmYP16lkEvgfFUnS1DPynuraovQp6ZcvWVdqVpyAEHBX9V3y5hSmTx0wTSsB7oO0hb++idqhAFVIGE441fnkVxX6I3ryXEEH0HIwRZdyzi7zLGYt4mOLgs8tjTWsXSYRf5ZXzX8ZjaLGshxWaG7iCFX3Hb9dL1HHwbE3xshKPWnzGHTmeZgx4UPbnFk43Zfk2QW7opfE1rDnLwDTSoG0=
  app:
    master: git-lucky-search
    travis: git-lucky-test
